### ISSUE TITLE
Plugin freezes Rainmeter 4.5.18

### ISSUE THREAD

**Issue by teijiIshida** [cperryoh/HomeAssitant-Rainmeter#1]
Hello,

The plugin doesn't seem to work with Rainmeter 4.5.18. It freezes my Rainmeter, and I can't open it via the tray icon to change anything. As soon as I remove the HomeAssitant.dll from the C:\Program Files\Rainmeter\Plugins, then Rainmeter stop freezing.

**Comment by z0mb13k1ll** [comment]
I am on 4.3.1 and can confirm this is also an issue. totally freezes rainmeter until i remove it

**Comment by cperryoh** [comment]
It's been a bit since I've used this plugin personally. I'll take a look into this problem today and see what I can do.

**Comment by cperryoh** [comment]
> Hello,
> 
> The plugin doesn't seem to work with Rainmeter 4.5.18. It freezes my Rainmeter, and I can't open it via the tray icon to change anything. As soon as I remove the HomeAssitant.dll from the C:\Program Files\Rainmeter\Plugins, then Rainmeter stop freezing.

@teijiIshida 
Sorry for being so late on this, can you supply your configuration?

**Comment by teijiIshida** [comment]
Hi, sorry, I found another way to get HA data without using the dll. Maybe someone else can provide you with the info if they want to use your plugin.

**Comment by ThioJoe** [comment]
For me it stopped freezing when I set `port=8123`, which is the port I use for the web interface. Also make sure the 'server' variable is just the bare IP, like `192.168.1.200`, because if I did `https://192.168.1.200` it would freeze.

Still having issues with it getting the info though, says 'nan'

**Comment by cperryoh** [comment]
> For me it stopped freezing when I set `port=8123`, which is the port I use for the web interface. Also make sure the 'server' variable is just the bare IP, like `192.168.1.200`, because if I did `https://192.168.1.200` it would freeze.
> 
> Still having issues with it getting the info though, says 'nan'

Could you share the config that gives you that nan response?

**Comment by ThioJoe** [comment]
> > For me it stopped freezing when I set `port=8123`, which is the port I use for the web interface. Also make sure the 'server' variable is just the bare IP, like `192.168.1.200`, because if I did `https://192.168.1.200` it would freeze.
> > Still having issues with it getting the info though, says 'nan'
> 
> Could you share the config that gives you that nan response?

Here's the config:

```

[Rainmeter]
Update=1000
DynamicWindowSize=1

[Metadata]
Name=Home Assistant Input Number Display
Author=Your Name
Information=Displays the state value of the "input_number.flux_ct" entity from Home Assistant.
Version=1.0
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0

[HomeAssistantMeasure]
Measure=Plugin
Plugin=#SETTINGSPATH#\Plugins\HomeAssistantPlugin.dll
auth=xxx-my-long-live-access-token-placeholder-xxx
server=192.168.1.99
entityId=input_number.flux_ct
isInt=false
ssl=true
port=8123
#path=state

[InputNumberDisplay]
Meter=String
MeasureName=HomeAssistantMeasure
X=10
Y=10
FontSize=20
FontColor=255,255,255
SolidColor=0,0,0
Padding=10,10,10,10
AntiAlias=1
Text=%1

```

Note I renamed the DLL because it was spelled wrong.

I put a placeholder for the key. But I also tried a few other things like a different entity that was an on/off switch, and disabling SSL on the home assistant server.

**Comment by ThioJoe** [comment]
> > For me it stopped freezing when I set `port=8123`, which is the port I use for the web interface. Also make sure the 'server' variable is just the bare IP, like `192.168.1.200`, because if I did `https://192.168.1.200` it would freeze.
> > Still having issues with it getting the info though, says 'nan'
> 
> Could you share the config that gives you that nan response?

I figured out the problem for the nan issue when not using SSL at least - the examples in the Readme all say:
`auth=`
but the parameter name is actually `authKey` not `auth`

So anyone copy and pasting the examples is going to have trouble.

Still seem to be having the issue when using SSL though.

**Comment by cperryoh** [comment]
yeah i need to update the example

**Comment by cperryoh** [comment]
> Still seem to be having the issue when using SSL though.

What issues are you having with SSL?

**Comment by cperryoh** [comment]
Recently, I updated the table of params but not the example. Currently how I have it written is there are 3 params that make up the server address: SSL, server, and port. I used to have them all together as on param but that got a bit confusing under the hood. So try having the server param as just the IP or host name, then set SSL to true.
