### ISSUE TITLE
Version 1.3 doesn't work

### ISSUE THREAD

**Issue by Null-Kelvin** [cperryoh/HomeAssitant-Rainmeter#2]
Rainmeter 4.5.18.3727 64-bit
Plugin 1.2 - work perfectly
Plugin 1.3 - error:
```
DBUG (12:33:15.501) HomeAssist\HomeAssist.ini - [Sensor_CO2_01]: 401: Unauthorized
ERRO (12:33:15.565) HomeAssist\HomeAssist.ini - [Sensor_CO2_01]: Unexpected character encountered while parsing number: :. Path '', line 1, position 3.
```

**Comment by cperryoh** [comment]
Can you show your .ini skin file that uses the plugin?

**Comment by Null-Kelvin** [comment]
[HomeAssist.txt](https://github.com/cperryoh/HomeAssitant-Rainmeter/files/14156137/HomeAssist.txt)

**Comment by cperryoh** [comment]
So on 1.3, I have slightly edited the config. it now looks like this.
|  Varible             | Description                                                                                                                                  | Default |
|     :----              |    :----                                                                                                                                           |  :----  |
| `authKey`            | Auth token from home assistant                                                                                               |`<empty>`|
| `server`                | Hassio server IP or domain name (192.168... or exampledoamin.com)                                       |`<empty>`|
| `path`(optional)    | Attribute path from entity                                                                                                      |`"state"`|
| `ssl`(optional)      | Should the api use ssl or not(true/false)                                                                                   |`false`  |
| `port`(optional)     | Port of the hassio server. Use -1 to denote no port and use the default web ports instead  |`-1`|                
| `isInt`(optional)      | Set to `true` if the attribute or state you are pulling is a number                                            |`false`  |
| `entityId`(optional) | Entity from home assistant to pull data from                                                                        |`<empty>`|

So assuming you were using a  normal config without ssl on the normal port, your config would be the following.
```
[hassioPlugin]
authKey=<your-key>
server=homeassistant.local
ssl =false
port =8123
isInt=true
entityId=sensor.room_temp
```
Let me know if this works.

**Comment by Null-Kelvin** [comment]
Yes, it works with authKey and ssl=false
Thank you!

**Comment by Luth1ng** [comment]
Hi,

I got the same error :
`Unexpected character encountered while parsing number: :. Path '', line 1, position 3. (hassio\hassio.ini - [hassio])`

My config : 
`[Rainmeter]
Update=5000

[Variables]
HASSIO_PLUG=#SETTINGSPATH#\Plugins\HomeAssistantPlugin.dll
HASSIO_SERV=myIpaddr
HASSIO_PORT=myPort
HASSIO_AUTH=myKey

[Style]
FontFace=Calibri
FontColor=#BaseColor#
AntiAlias=1
FontSize=8
SolidColor=0,0,0,1

[hassio]
Measure=Plugin
Plugin=#HASSIO_PLUG#
server=#HASSIO_SERV#
authKey=#HASSIO_AUTH#
port=#HASSIO_PORT#
entityId=switch.plug1
ssl=false
isInt=true

[example]
Meter=String
MeasureName=hassio
FontSize=12
X=400
Y=70
StringAlign=Center
Text=Entity: %1`

Any idea?
